INSERT INTO roles(name)
SELECT 'ROLE_EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_EMPLOYEE');

INSERT INTO roles(name)
SELECT 'ROLE_HR'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_HR');

INSERT INTO roles(name)
SELECT 'ROLE_MANAGER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name='ROLE_MANAGER');
